<?php

/**
* String Class
 *
 * @package		Berlinto
 * @subpackage	Common
 * @category	Common
 * @author		Carl McDade
 * @link		http://berlinto.com
 * 
 * description: the properties array is the a collection of parameters to set for manipulating the string
 * 
 * 
 * @string 
 * 
 */


class common_string
{
	function manipulate($string, $properties = array())
	{		
		// look for template for this element
		
	}
}

?>
